<a href="https://colab.research.google.com/github/thayyilakul/JForceMLAssignment/blob/main/JForceMLAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'2.18.0'

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/gdrive/MyDrive/project/consumer_complaints_copy.csv')
df.head()

date_received          product                  sub_product  \
0    12-05-2014  Debt collection                     Mortgage   
1    11-10-2014         Mortgage               Other mortgage   
2    08/26/2015         Mortgage               Other mortgage   
3    01/16/2014  Debt collection                     Mortgage   
4    06/25/2015         Mortgage  Conventional fixed mortgage   

                                      issue  \
0           Disclosure verification of debt   
1  Loan servicing, payments, escrow account   
2  Loan modification,collection,foreclosure   
3           Disclosure verification of debt   
4  Application, originator, mortgage broker   

                              sub_issue  \
0  Not given enough info to verify debt   
1                                   NaN   
2                                   NaN   
3  Not given enough info to verify debt   
4                                   NaN   

                        consumer_complaint_narrative company_public_response  \
0                                                NaN                     NaN   
1                                                NaN                     NaN   
2                                                NaN                     NaN   
3                                                NaN                     NaN   
4  My mortgage company has misrepresented themsel...                     NaN   

                                    company state zipcode tags  \
0  (Former)Shapiro, Swertfeger & Hasty, LLP    GA   30005  NaN   
1  (Former)Shapiro, Swertfeger & Hasty, LLP    DE   19803  NaN   
2  (Former)Shapiro, Swertfeger & Hasty, LLP    GA   30014  NaN   
3  (Former)Shapiro, Swertfeger & Hasty, LLP    GA   30087  NaN   
4      1st 2nd Mortgage Company Of NJ, Inc.    NJ   074XX  NaN   

  consumer_consent_provided submitted_via date_sent_to_company  \
0                       NaN      Referral           12-12-2014   
1                       NaN      Referral           11/19/2014   
2                       NaN      Referral           09-08-2015   
3                       NaN      Referral           02-11-2014   
4          Consent provided           Web           07/22/2015   

  company_response_to_consumer timely_response consumer_disputed?  \
0            Untimely response              No                 No   
1            Untimely response              No                 No   
2            Untimely response              No                 No   
3            Untimely response              No                 No   
4                       Closed             Yes                 No   

   complaint_id  
0       1144671  
1       1109287  
2       1536776  
3        671539  
4       1437506

In [4]:
data = {
  "product": [data for data in df['product']],
  "sub_product": [data for data in df['sub_product']],
  "issue": [data for data in df['issue']],
  "sub_issue": [data for data in df['sub_issue']],
}
new_df = pd.DataFrame(data)
new_df.head()

product                  sub_product  \
0  Debt collection                     Mortgage   
1         Mortgage               Other mortgage   
2         Mortgage               Other mortgage   
3  Debt collection                     Mortgage   
4         Mortgage  Conventional fixed mortgage   

                                      issue  \
0           Disclosure verification of debt   
1  Loan servicing, payments, escrow account   
2  Loan modification,collection,foreclosure   
3           Disclosure verification of debt   
4  Application, originator, mortgage broker   

                              sub_issue  
0  Not given enough info to verify debt  
1                                   NaN  
2                                   NaN  
3  Not given enough info to verify debt  
4                                   NaN

In [5]:
len(new_df)

555957

In [6]:
new_df.isna().sum()

product             0
sub_product    158322
issue               0
sub_issue      343335
dtype: int64

In [7]:
new_df.value_counts('product')

product
Mortgage                   186475
Debt collection            101052
Credit reporting            91854
Credit card                 66468
Bank account or service     62563
Consumer Loan               20990
Student loan                15839
Payday loan                  3877
Money transfers              3812
Prepaid card                 2470
Other financial service       557
Name: count, dtype: int64

In [8]:
new_df.value_counts('sub_product')

sub_product
Other mortgage                            74319
Conventional fixed mortgage               57182
Checking account                          44369
Other (i.e. phone, health club, etc.)     29617
I do not know                             21634
Conventional adjustable mortgage (ARM)    20941
Credit card                               20825
FHA mortgage                              19152
Non-federal student loan                  17969
Medical                                   13297
Vehicle loan                              12168
Other bank product/service                10895
Payday loan                                9684
Home equity loan or line of credit         8944
Installment loan                           5279
Savings account                            3996
VA mortgage                                3735
Mortgage                                   3433
(CD) Certificate of deposit                2839
Auto                                       2523
International money transfer               2035
Federal student loan                       1786
Domestic (US) money transfer               1777
Vehicle lease                              1639
Reverse mortgage                           1537
Personal line of credit                    1516
General purpose card                       1165
Second mortgage                             665
Cashing a check without an account          464
Title loan                                  329
Payroll card                                313
Mobile wallet                               240
Gift or merchant card                       225
Government benefit payment card             225
Check cashing                               156
ID prepaid card                             144
Debt settlement                             142
Other special purpose card                  123
Money order                                  71
Pawn loan                                    59
Credit repair                                54
Traveler’s/Cashier’s checks              51
Foreign currency exchange                    43
Refund anticipation check                    40
Transit card                                 30
Electronic Benefit Transfer / EBT card        5
Name: count, dtype: int64

In [9]:
new_df.value_counts('issue')

issue
Loan modification,collection,foreclosure    97191
Incorrect information on credit report      66718
Loan servicing, payments, escrow account    60375
Cont'd attempts collect debt not owed       42285
Account opening, closing, or management     26661
                                            ...  
Lost or stolen money order                     25
Incorrect exchange rate                        16
Lender damaged or destroyed vehicle             5
Lender sold the property                        5
Lender damaged or destroyed property            1
Name: count, Length: 95, dtype: int64

In [10]:
new_df.value_counts('sub_issue')

sub_issue
Account status                              26798
Debt is not mine                            26285
Information is not mine                     19900
Not given enough info to verify debt        12496
Debt was paid                               11328
                                            ...  
Receiving unwanted marketing/advertising      166
Report shared with employer w/o consent       127
Received marketing offer after opted out      125
Qualify for a better loan than offered        107
Insurance terms                                 4
Name: count, Length: 68, dtype: int64

In [11]:
import random
random_index = random.randint(0, len(new_df) - 5)
for row in df[['issue', 'sub_issue', 'product', 'sub_product']][random_index: random_index + 5].itertuples():
  _, issue, sub_issue, product, sub_product = row
  print(f'Issue - {issue}')
  print(f'Sub-Issue - {sub_issue}')
  print(f'Product - {product}')
  print(f'Sub-Product - {sub_product}')
  print('----')

Issue - Problems caused by my funds being low
Sub-Issue - nan
Product - Bank account or service
Sub-Product - Checking account
----
Issue - Loan modification,collection,foreclosure
Sub-Issue - nan
Product - Mortgage
Sub-Product - Other mortgage
----
Issue - Problems caused by my funds being low
Sub-Issue - nan
Product - Bank account or service
Sub-Product - Other bank product/service
----
Issue - Deposits and withdrawals
Sub-Issue - nan
Product - Bank account or service
Sub-Product - Checking account
----
Issue - Using a debit or ATM card
Sub-Issue - nan
Product - Bank account or service
Sub-Product - Checking account
----


In [12]:
product_count = list(set([data for data in new_df['product']]))
sub_product_count = list(set([data for data in new_df['sub_product']]))

In [13]:
product_count

['Other financial service',
 'Student loan',
 'Mortgage',
 'Consumer Loan',
 'Bank account or service',
 'Prepaid card',
 'Payday loan',
 'Credit reporting',
 'Credit card',
 'Money transfers',
 'Debt collection']

In [14]:
sub_product_count

['Title loan',
 'Transit card',
 'Conventional fixed mortgage',
 'Personal line of credit',
 'Vehicle loan',
 'Money order',
 'Vehicle lease',
 'Refund anticipation check',
 'Pawn loan',
 'Federal student loan',
 nan,
 'Savings account',
 'Checking account',
 'Debt settlement',
 'Payday loan',
 'Other special purpose card',
 'International money transfer',
 'Travelerâ\x80\x99s/Cashierâ\x80\x99s checks',
 'Credit card',
 'Installment loan',
 'General purpose card',
 'Reverse mortgage',
 'Other mortgage',
 'Medical',
 'Mobile wallet',
 'Cashing a check without an account',
 'Mortgage',
 'Foreign currency exchange',
 'FHA mortgage',
 'Non-federal student loan',
 'VA mortgage',
 'I do not know',
 'Other (i.e. phone, health club, etc.)',
 'Payroll card',
 'Conventional adjustable mortgage (ARM)',
 'Home equity loan or line of credit',
 'Check cashing',
 'Gift or merchant card',
 '(CD) Certificate of deposit',
 'Government benefit payment card',
 'ID prepaid card',
 'Second mortgage',
 'Elec

In [15]:
test_df = new_df

In [16]:
test_df['product_index'] = test_df['product'].apply(lambda x: product_count.index(x))
test_df['sub_product_index'] = test_df['sub_product'].apply(lambda x: sub_product_count.index(x))
test_df.head()

product                  sub_product  \
0  Debt collection                     Mortgage   
1         Mortgage               Other mortgage   
2         Mortgage               Other mortgage   
3  Debt collection                     Mortgage   
4         Mortgage  Conventional fixed mortgage   

                                      issue  \
0           Disclosure verification of debt   
1  Loan servicing, payments, escrow account   
2  Loan modification,collection,foreclosure   
3           Disclosure verification of debt   
4  Application, originator, mortgage broker   

                              sub_issue  product_index  sub_product_index  
0  Not given enough info to verify debt             10                 26  
1                                   NaN              2                 22  
2                                   NaN              2                 22  
3  Not given enough info to verify debt             10                 26  
4                                   NaN              2                  2

In [17]:
test_df.tail()

product                            sub_product  \
555952  Debt collection               Non-federal student loan   
555953  Debt collection               Non-federal student loan   
555954  Debt collection  Other (i.e. phone, health club, etc.)   
555955  Debt collection                            Credit card   
555956  Debt collection                            Credit card   

                                        issue  \
555952    Improper contact or sharing of info   
555953  Cont'd attempts collect debt not owed   
555954        Disclosure verification of debt   
555955        Disclosure verification of debt   
555956     False statements or representation   

                                    sub_issue  product_index  \
555952  Contacted employer after asked not to             10   
555953      Debt was discharged in bankruptcy             10   
555954   Not given enough info to verify debt             10   
555955   Not given enough info to verify debt             10   
555956   Impersonated an attorney or official             10   

        sub_product_index  
555952                 29  
555953                 29  
555954                 32  
555955                 18  
555956                 18

In [18]:
import sklearn
sklearn.__version__

'1.6.1'

In [19]:
train_vals = {
  "issue": [data for data in df['issue']],
  "sub_issue": [data for data in df['sub_issue']],
}

train_df= pd.DataFrame(train_vals)
train_df.head()

issue  \
0           Disclosure verification of debt   
1  Loan servicing, payments, escrow account   
2  Loan modification,collection,foreclosure   
3           Disclosure verification of debt   
4  Application, originator, mortgage broker   

                              sub_issue  
0  Not given enough info to verify debt  
1                                   NaN  
2                                   NaN  
3  Not given enough info to verify debt  
4                                   NaN

In [20]:
test_df['product_index'] = test_df['product'].apply(lambda x: product_count.index(x))
test_df['sub_product_index'] = test_df['sub_product'].apply(lambda x: sub_product_count.index(x))
test_df.head()

product                  sub_product  \
0  Debt collection                     Mortgage   
1         Mortgage               Other mortgage   
2         Mortgage               Other mortgage   
3  Debt collection                     Mortgage   
4         Mortgage  Conventional fixed mortgage   

                                      issue  \
0           Disclosure verification of debt   
1  Loan servicing, payments, escrow account   
2  Loan modification,collection,foreclosure   
3           Disclosure verification of debt   
4  Application, originator, mortgage broker   

                              sub_issue  product_index  sub_product_index  
0  Not given enough info to verify debt             10                 26  
1                                   NaN              2                 22  
2                                   NaN              2                 22  
3  Not given enough info to verify debt             10                 26  
4                                   NaN              2                  2

In [21]:
from sklearn.model_selection import train_test_split

train_sentences, val_sentences, train_product_labels, val_product_labels = train_test_split(train_df['issue'].to_numpy(),
                                                                            test_df['product_index'].to_numpy(),
                                                                            test_size = 0.2,
                                                                            random_state = 42)

train2_sentences, val2_sentences, train_sub_product_labels, val_sub_product_labels = train_test_split(train_df['issue'].to_numpy(),
                                                                            test_df['sub_product_index'].to_numpy(),
                                                                            test_size = 0.2,
                                                                            random_state = 42)

len(train_sentences), len(val_sentences), len(train_product_labels), len(val_product_labels), len(train_sub_product_labels), len(val_sub_product_labels)

(444765, 111192, 444765, 111192, 444765, 111192)

In [22]:
train_sentences[:10], train_product_labels[:10], train_sub_product_labels[:10]

(array(['Problems caused by my funds being low',
        'Account opening, closing, or management',
        'Loan modification,collection,foreclosure',
        'Loan modification,collection,foreclosure',
        'Taking out the loan or lease',
        "Credit reporting company's investigation",
        'Taking/threatening an illegal action',
        'Disclosure verification of debt',
        "Received a loan I didn't apply for",
        'Unable to get credit report/credit score'], dtype=object),
 array([ 4,  4,  2,  2,  3,  7, 10, 10,  6,  7]),
 array([12, 46,  2, 22,  4, 10, 18, 32, 14, 10]))

In [23]:
from tensorflow.keras.layers import TextVectorization

max_length = 10
max_vocab_length = 1000

text_vectorizer = TextVectorization(
    max_tokens = max_vocab_length,
    standardize = 'lower_and_strip_punctuation',
    split = 'whitespace',
    ngrams = None,
    output_mode = 'int',
    output_sequence_length = max_length
)

In [24]:
text_vectorizer.adapt(train_sentences)

In [25]:
sample = random.choice(train_sentences)
print(f'Sample sentence : {sample}')
print(f'Text Vectorizer : {text_vectorizer([sample])}')

Sample sentence : Credit card protection / Debt protection
Text Vectorizer : [[ 3 65 68 12 68  0  0  0  0  0]]


In [26]:
vocab_words = text_vectorizer.get_vocabulary()
top_5_words = vocab_words[:5]
bottom_5_words = vocab_words[-5:]
print(f'Top 5 Words : {top_5_words}')
print(f'Bottom 5 Words : {bottom_5_words}')

Top 5 Words : ['', '[UNK]', np.str_('loan'), np.str_('credit'), np.str_('modificationcollectionforeclosure')]
Bottom 5 Words : [np.str_('order'), np.str_('exchange'), np.str_('property'), np.str_('destroyed'), np.str_('damaged')]


In [27]:
from tensorflow.keras import layers

embedding = layers.Embedding(
    input_dim = max_vocab_length,
    output_dim = 128,
    embeddings_initializer = 'uniform',
    input_length = max_length,
    name = 'embedding_1'
)

embedding

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


<Embedding name=embedding_1, built=False>

In [28]:
sample_train_sentence = random.choice(train_sentences)
print(f'Original Sentence : {sample_train_sentence}')
sample_embed = embedding(text_vectorizer([sample_train_sentence]))
sample_embed

Original Sentence : Incorrect information on credit report


<tf.Tensor: shape=(1, 10, 128), dtype=float32, numpy=
array([[[ 0.04158599,  0.00337141,  0.02722807, ...,  0.04799685,
          0.0018301 , -0.01586635],
        [ 0.02712573,  0.02841027, -0.02827858, ..., -0.04460821,
          0.03969384, -0.029803  ],
        [ 0.02272551,  0.04299435, -0.01309657, ..., -0.03373405,
          0.03396987,  0.04320927],
        ...,
        [-0.00331759,  0.03326787, -0.0169156 , ...,  0.02321428,
          0.03266609, -0.00015091],
        [-0.00331759,  0.03326787, -0.0169156 , ...,  0.02321428,
          0.03266609, -0.00015091],
        [-0.00331759,  0.03326787, -0.0169156 , ...,  0.02321428,
          0.03266609, -0.00015091]]], dtype=float32)>

In [29]:
sample_embed[0][0]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([ 0.04158599,  0.00337141,  0.02722807,  0.03280449, -0.02389685,
       -0.02869213,  0.04148102,  0.0148443 ,  0.01403213, -0.02538118,
       -0.04109622, -0.04905934, -0.0387478 , -0.03200728,  0.03435067,
       -0.04136448, -0.02782463,  0.02309385,  0.001135  ,  0.02671465,
       -0.01916758, -0.01155001,  0.01986352,  0.02946904, -0.02628397,
        0.03011811,  0.03562788, -0.0418463 , -0.04541773, -0.03168526,
       -0.00669905, -0.04774364,  0.01088895,  0.02273912,  0.04706507,
        0.03516027, -0.01370267,  0.02946853, -0.00522833, -0.02266827,
       -0.00015539,  0.00399991, -0.00182347,  0.04774967,  0.01047336,
       -0.02849355, -0.02492139,  0.04859874,  0.02006737, -0.03187688,
        0.03384284,  0.04184375,  0.03177586,  0.00891186, -0.01428832,
        0.02291289, -0.01023288,  0.02231565, -0.04930432,  0.03991703,
       -0.03946488,  0.01508694, -0.02041353, -0.03859434, -0.03175398,
       -0.000896

In [30]:
# from sklearn.pipeline import Pipeline
# from sklearn.naive_bayes import MultinomialNB
# from sklearn.feature_extraction.text import TfidfVectorizer

# model_0 = Pipeline([
#     ('tfidf', TfidfVectorizer()),
#     ('clf', MultinomialNB())
# ])

# model_0.fit(train_sentences, train_product_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [31]:
# print(f'Baseline accuracy = {model_0.score(val_sentences, val_product_labels) * 100:2f} %')

Baseline accuracy = 98.361393 %


In [32]:
# baseline_preds = model_0.predict(val_sentences)
# baseline_preds

array([ 2,  4,  2, ...,  8, 10,  2])

In [33]:
# model_1 = Pipeline([
#     ('tfidf', TfidfVectorizer()),
#     ('clf', MultinomialNB())
# ])

# model_1.fit(train_sentences, train_sub_product_labels)

In [46]:
tf.random.set_seed(42)

model_1_embedding = layers.Embedding(input_dim = max_vocab_length,
                                    output_dim = 128,
                                    embeddings_initializer = 'uniform',
                                    input_length = max_length,
                                    name = 'embedding_1')

inputs = layers.Input(shape = (1, ), dtype = 'string')
x = text_vectorizer(inputs)
x = model_1_embedding(x)
x = layers.LSTM(64)(x)
x = layers.Dense(4, activation = 'relu')(x)
x = layers.Dense(4, activation = 'relu')(x)
outputs = layers.Dense(len(product_count), activation = 'softmax')(x)
model_1 = tf.keras.Model(inputs, outputs, name = 'model_1_LSTM')

In [52]:
model_1.compile(loss = 'sparse_categorical_crossentropy',
                optimizer = 'adam',
                metrics = ['accuracy'])

In [53]:
model_1.summary()

Model: "model_1_LSTM"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)           │ (None, 1)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ text_vectorization                   │ (None, 10)                  │               0 │
│ (TextVectorization)                  │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding_1 (Embedding)              │ (None, 10, 128)             │         128,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_3 (LSTM)                        │ (None, 64)                  │          49,408 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 4)                   │             260 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 4)                   │              20 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 11)                  │              55 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 177,743 (694.31 KB)

 Trainable params: 177,743 (694.31 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
train_sentences.shape, train_product_labels.shape, val_sentences.shape, val_product_labels.shape

((444765,), (444765,), (111192,), (111192,))

In [56]:
model_1.fit(train_sentences,
            train_product_labels,
            epochs = 5,
            validation_data = (val_sentences, val_product_labels))

Epoch 1/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 181s 13ms/step - accuracy: 0.7481 - loss: 0.6606 - val_accuracy: 0.8414 - val_loss: 0.4029
Epoch 2/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 150s 11ms/step - accuracy: 0.8340 - loss: 0.4184 - val_accuracy: 0.8169 - val_loss: 0.4747
Epoch 3/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 140s 10ms/step - accuracy: 0.8403 - loss: 0.4324 - val_accuracy: 0.8561 - val_loss: 0.3720
Epoch 4/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 148s 11ms/step - accuracy: 0.8558 - loss: 0.3666 - val_accuracy: 0.8561 - val_loss: 0.3638
Epoch 5/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 154s 11ms/step - accuracy: 0.8559 - loss: 0.3611 - val_accuracy: 0.8561 - val_loss: 0.3625


In [57]:
y_probs = model_1.predict(val_sentences)
y_probs[:5]

3475/3475 ━━━━━━━━━━━━━━━━━━━━ 12s 3ms/step


array([[2.0753088e-11, 3.9536638e-12, 7.2970331e-01, 1.2286558e-03,
        2.4038164e-01, 3.3395658e-11, 3.4888958e-12, 7.7606839e-14,
        2.1961773e-07, 4.7518791e-11, 2.8686108e-02],
       [2.0753088e-11, 3.9536638e-12, 7.2970331e-01, 1.2286558e-03,
        2.4038164e-01, 3.3395658e-11, 3.4888958e-12, 7.7606839e-14,
        2.1961773e-07, 4.7518791e-11, 2.8686108e-02],
       [2.0753088e-11, 3.9536638e-12, 7.2970331e-01, 1.2286558e-03,
        2.4038164e-01, 3.3395658e-11, 3.4888958e-12, 7.7606839e-14,
        2.1961773e-07, 4.7518791e-11, 2.8686108e-02],
       [2.0753088e-11, 3.9536638e-12, 7.2970331e-01, 1.2286558e-03,
        2.4038164e-01, 3.3395658e-11, 3.4888958e-12, 7.7606839e-14,
        2.1961773e-07, 4.7518791e-11, 2.8686108e-02],
       [2.0753088e-11, 3.9536638e-12, 7.2970331e-01, 1.2286558e-03,
        2.4038164e-01, 3.3395658e-11, 3.4888958e-12, 7.7606839e-14,
        2.1961773e-07, 4.7518791e-11, 2.8686108e-02]], dtype=float32)

In [58]:
y_probs[0].argmax(), product_count[y_probs[0].argmax()]

(np.int64(2), 'Mortgage')

In [59]:
y_preds = y_probs.argmax(axis = 1)
y_preds[:10]

array([ 2,  2,  2,  2,  2, 10,  2,  2,  6,  2])

In [61]:
# For predicting product
test_samples = random.sample(sorted(train_sentences), 10)
for test_sample in test_samples:
    prob = model_1.predict(np.array([test_sample], dtype = 'object'))
    arg_pred = prob.argmax()
    print(f'Prediction : {product_count[arg_pred]}')
    print(f'Text: \n{test_sample}\n')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Prediction : Credit reporting
Text: 
Incorrect information on credit report

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Prediction : Mortgage
Text: 
Loan modification,collection,foreclosure

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Prediction : Mortgage
Text: 
Account opening, closing, or management

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Prediction : Mortgage
Text: 
Account opening, closing, or management

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Prediction : Mortgage
Text: 
Improper contact or sharing of info

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Prediction : Credit card
Text: 
Credit determination

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Prediction : Debt collection
Text: 
Communication tactics

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Prediction : Credit reporting
Text: 
Unable to get credit report/credit score

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Prediction : Consumer Loan
Text: 
Problems when you are unable to pay

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Pre

In [ ]:
# model_1_preds = tf.squeeze(tf.round(model_1_pred_probs))
# model_1_preds[:10]

In [ ]:
# from sklearn.metrics import accuracy_score, precision_recall_fscore_support

# model_accuracy = accuracy_score(val_product_labels, baseline_preds) * 100
# model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(val_product_labels, baseline_preds, average = 'weighted')

In [106]:
tf.random.set_seed(42)

model_2_embedding = layers.Embedding(input_dim = max_vocab_length,
                                    output_dim = 128,
                                    embeddings_initializer = 'uniform',
                                    input_length = max_length,
                                    name = 'embedding_2')

inputs = layers.Input(shape = (1, ), dtype = 'string')
x = text_vectorizer(inputs)
x = model_2_embedding(x)
x = layers.LSTM(64)(x)
x = layers.Dense(10, activation = 'relu')(x)
x = layers.Dense(10, activation = 'relu')(x)
x = layers.Dense(10, activation = 'relu')(x)
x = layers.Dense(10, activation = 'relu')(x)
outputs = layers.Dense(len(sub_product_count), activation = 'softmax')(x)
model_2 = tf.keras.Model(inputs, outputs, name = 'model_2_GRU')

In [107]:
model_2.compile(loss = 'sparse_categorical_crossentropy',
                optimizer = 'adam',
                metrics = ['accuracy'])

In [108]:
model_2.summary()

Model: "model_2_GRU"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)           │ (None, 1)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ text_vectorization                   │ (None, 10)                  │               0 │
│ (TextVectorization)                  │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ embedding_2 (Embedding)              │ (None, 10, 128)             │         128,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_6 (LSTM)                        │ (None, 64)                  │          49,408 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 10)                  │             650 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 47)                  │             517 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 178,905 (698.85 KB)

 Trainable params: 178,905 (698.85 KB)

 Non-trainable params: 0 (0.00 B)

In [109]:
model_2.fit(train2_sentences,
            train_sub_product_labels,
            epochs = 5,
            validation_data = (val2_sentences, val_sub_product_labels))

Epoch 1/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 173s 12ms/step - accuracy: 0.5768 - loss: 1.1806 - val_accuracy: 0.6232 - val_loss: 0.9840
Epoch 2/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 192s 12ms/step - accuracy: 0.6212 - loss: 0.9873 - val_accuracy: 0.6242 - val_loss: 0.9806
Epoch 3/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 195s 11ms/step - accuracy: 0.6236 - loss: 0.9790 - val_accuracy: 0.6242 - val_loss: 0.9773
Epoch 4/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 153s 11ms/step - accuracy: 0.6244 - loss: 0.9769 - val_accuracy: 0.6242 - val_loss: 0.9759
Epoch 5/5
13899/13899 ━━━━━━━━━━━━━━━━━━━━ 207s 11ms/step - accuracy: 0.6241 - loss: 0.9788 - val_accuracy: 0.6242 - val_loss: 0.9756


In [91]:
# For predicting product
test_samples = random.sample(sorted(train2_sentences), 10)
for test_sample in test_samples:
    prob = model_2.predict(np.array([test_sample], dtype = 'object'))
    arg_pred = prob.argmax()
    print(f'Prediction : {sub_product_count[arg_pred]}')
    print(f'Text: \n{test_sample}\n')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 252ms/step
Prediction : I do not know
Text: 
Cont'd attempts collect debt not owed

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
Prediction : Credit card
Text: 
Taking/threatening an illegal action

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Prediction : Vehicle loan
Text: 
Taking out the loan or lease

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Prediction : Checking account
Text: 
Deposits and withdrawals

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Prediction : nan
Text: 
Incorrect information on credit report

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Prediction : Checking account
Text: 
Account opening, closing, or management

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Prediction : Other (i.e. phone, health club, etc.)
Text: 
False statements or representation

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Prediction : Other mortgage
Text: 
Loan modification,collection,foreclosure

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Prediction : nan
Text: 
Incorrect information on credit report

1/1 ━━━━━━━

In [92]:
def argmax(model, sentence):
  prod_prob = model.predict(np.array([sentence], dtype = 'object'))
  return prod_prob.argmax()

def response(product_arg_pred, sub_prod_arg_pred, sentence):
    print(f'Product Prediction: {product_count[product_arg_pred]}')
    print(f'Sub-Product Prediction : {sub_product_count[sub_prod_arg_pred]}')
    print(f'Text: \n{sentence}\n')

In [111]:
def predict_sentences(sentence = False):
  if(sentence):
    product_arg_pred = argmax(model_1, sentence)
    sub_prod_arg_pred = argmax(model_2, sentence)
    response(product_arg_pred, sub_prod_arg_pred, sentence)
  else:
    test_samples = random.sample(sorted(train2_sentences), 10)
    for test_sample in test_samples:
      product_arg_pred = argmax(model_1, test_sample)
      sub_prod_arg_pred = argmax(model_2, test_sample)
      response(product_arg_pred, sub_prod_arg_pred, test_sample)

In [94]:
predict_sentences()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Product Prediction: Credit card
Sub-Product Prediction : nan
Text: 
Collection practices

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
Product Prediction: Credit reporting
Sub-Product Prediction : nan
Text: 
Incorrect information on credit report

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Product Prediction: Mortgage
Sub-Product Prediction : Other mortgage
Text: 
Loan modification,collection,foreclosure

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
Product Prediction: Mortgage
Sub-Product Prediction : Other mortgage
Text: 
Loan modification,collection,foreclosure

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Product Prediction: Debt collection
Sub-Product Prediction : I do not know
Text: 
Cont'd attempts collect debt not owed

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━

In [112]:
predict_sentences('Managing the line of credit')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 233ms/step
Product Prediction: Consumer Loan
Sub-Product Prediction : Personal line of credit
Text: 
Managing the line of credit

